### ISSUE TITLE
a error happen when PricingModule Initialize

### ISSUE THREAD

**Issue by JingLi-kooboo** [VirtoCommerce/vc-module-pricing#1]
Assembly "VirtoCommerce. PricingModule. Data, Version = 2.11.0.0, Culture = neutral, PublicKeyToken = null" type of "VirtoCommerce. PricingModule. Data. Services. PricingServiceImpl" method "CreatePrices" no implementation.
  StackTrace: at VirtoCommerce.PricingModule.Web.Module.Initialize()
   at VirtoCommerce.Platform.Web.Modularity.ModuleInitializer.Initialize(ModuleInfo moduleInfo) location E:\vc-platform-master\VirtoCommerce.Platform.Web\Modularity\ModuleInitializer.cs: line number 64

**Comment by tatarincev** [comment]
It was erroneous release of core.module 2.15.3. Now It reverted to 2.15.1. To repair you system just cleanup you platform App_Data/Modules folder and replace in /VirtoCommerce.Core module in Modules folder by old version from https://github.com/VirtoCommerce/vc-module-core/releases/download/v2.15.1/VirtoCommerce.Core_2.15.1.zip

**Comment by JingLi-kooboo** [comment]
thanks
