### ISSUE TITLE
Pricing blade opens to the left of the other blades

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-pricing#113]
Please provide detailed information about your issue, thank you!

Version info: 
- Platform version: 3.29

### Expected behavior
Should open to the right

### Actual behavior
![image](https://user-images.githubusercontent.com/1566470/100810672-cd538280-33ed-11eb-917e-19cf8533ca31.png)

### Steps to reproduce
1. Go to QA webstore platform
2. Navigate -> product -> price list -> click prices

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6283 has been created
