### ISSUE TITLE
Set new pricelist assignments are only possible for the first 20 catalogs

### ISSUE THREAD

**Issue by corneliusmunz** [VirtoCommerce/vc-module-pricing#121]
Please provide detailed information about your issue, thank you!

Version info: 
- Browser version: Chrome 88.0.4324.104
- Platform version: 3.39.0
- Module version: 3.15.0

### Expected behavior
Mapping of pricelist to catalog should be possible for all available catalogs and not only for the first 20 catalogs

### Actual behavior
The pulldown menu in the `../item/assignment-detail.js` blade will render only 20 catalogs 0..19 becaus the GET query to catalogs have no "take" parameter and the default implementation is used which means only the first 20 catalogs will be fetched. 

For the pricelists there is a  `take=1000` implemented. 

### Steps to reproduce
1. Add more than 20 catalogs to the setup
2. Go to pricing/Price list assignments/ 
3. Add a new assignment and open the catalog pull-down menu
4. Only the first 20 will be visible

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-6852 has been created

**Comment by corneliusmunz** [comment]
@mvktsk any news on that? Without a fix we have to do the assignments manually in the DB or via the API and can not use the admin frontend.

**Comment by OlegoO** [comment]
@corneliusmunz  I prioritized it and assigned with dev team. I will ping when have more details
 
FUY: Please submit a new issue via https://help.virtocommerce.com/support/home or send email to support@virtocommerce.com, so we can prioritize and resolve it faster.

**Comment by Vectorfield4** [comment]
Fixed in release https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/3.17.0
