### ISSUE TITLE
PricelistAssignment Change Event

### ISSUE THREAD

**Issue by wsimon** [VirtoCommerce/vc-module-pricing#134]
There is a price changed event for when prices change, but there doesn't seem to be an event fired for PricelistAssignment changes. 
Is that something that could be added? Either a new Event type or using the existing PriceChangedEvent would work.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7354 has been created

**Comment by OlegoO** [comment]
Hi,

From the code
https://github.com/VirtoCommerce/vc-module-pricing/blob/62113712bbec119cb06e8d92eaa8142aa56502ab/src/VirtoCommerce.PricingModule.Data/Services/PricingServiceImpl.cs#L348-L376

No events for PricelistAssignment, yet. 

Could you explain your scenario?  

So, We can properly implement it.

**Comment by wsimon** [comment]
We have our own external cache of prices that we use that we need to refresh when the assignments change.

**Comment by OlegoO** [comment]
@wsimon Got it, will extend it soon

**Comment by OlegoO** [comment]
https://github.com/VirtoCommerce/vc-module-pricing/pull/136

**Comment by OlegoO** [comment]
@wsimon please install and test alpha release
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.20.0-alpha.499.zip

**Comment by wsimon** [comment]
@OlegoO Sorry for the delay. I tried version 3.21.0 and the new events for pricelist and pricelistAssignments are working correctly. Thanks!
