### ISSUE TITLE
Unexpected TotalCount logic in PriceSearchResult

### ISSUE THREAD

**Issue by Grosam** [VirtoCommerce/vc-module-pricing#195]
Version info: 
- Platform version: 3.270.0
- Module version: 3.216.0

When `GET /api/catalog/products/prices/search` endpoint is used to get prices without specifying the `keyword` parameter, the `totalCount` field contains total count of all relevant items which can be bigger than the number specified in the `take` parameter. 

However, when the `keyword` parameter is specified, the `totalCount` field contains minimum of two numbers: `take` argument and returned `items` count.

It's expected that when the `keyword` parameter is specified, the `totalCount` field contains total count of all relevant items.

### Steps to reproduce
1. Set up products and a pricelist so that the pricelist has at least two prices that can be found by a keyword.
2. Make an HTTP request to `GET /api/catalog/products/prices/search` with the following paramters:
- pricelistIds = <the pricelist id from point 1>
- keyword = <the keyword from point 1>
- take = 1
3. Notice that the `totalCount` is equal to 1 even though there is on more relevant price that can be retrieved if `take` is equal to 2.
4. Make an HTTP request to `GET /api/catalog/products/prices/search` with the following paramters:
- pricelistIds = <the pricelist id from point 1>
- keyword = <the keyword from point 1>
- take = 2
5. Notice that the `totalCount` is equal to 2

**Comment by OlegoO** [comment]
Fixed https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/3.220.0
