### ISSUE TITLE
Missing value in product index document after reindexing due to price change

### ISSUE THREAD

**Issue by Grosam** [VirtoCommerce/vc-module-pricing#199]
When Elasticsearch module is used and the option "Enable event-based indexing for pricing entities" is on and a product is reindexed due to its price change, the product index document does not have "product" value in "is" field so if you specify "is:product" filter for products GraphQL query, you will not get such product in the result list.

Version info: 
- Platform version: 3.293.8
- Module version: 3.219.0

### Steps to reproduce
1. Configure Elasticsearch
2. Create a product
3. Enable the option "Enable event-based indexing for pricing entities" in Pricing settings
4. Add a price for the product
5. Inspect the product index document

Noticed that if a product is reindexed due to an inventory change and similar option is enabled, the product has "product" value in "is" field.

**Comment by AlexTzykin** [comment]
@OlegoO https://virtocommerce.atlassian.net/browse/PT-13147

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8417 has been created

**Comment by ekuvirto** [comment]
https://github.com/VirtoCommerce/vc-module-search/releases/tag/3.406.0
