### ISSUE TITLE
Simplify price management when price start and end date are not required

### ISSUE THREAD

**Issue by Woland2k** [VirtoCommerce/vc-module-pricing#33]
For prices there is a new option to add start and end dates, we need to have a switch that disables that features at least visually in admin (preferably both visually and logically) so price management doesn't become more complicated when it is not needed.

**Comment by OlegoO** [comment]
By default, the feature is hidden. Can be activated in List View
![image](https://user-images.githubusercontent.com/7639413/114365808-1c1edf00-9b7b-11eb-8ea6-f54a113738ec.png)
