### ISSUE TITLE
Pricing module UX improvements

### ISSUE THREAD

**Issue by avas** [VirtoCommerce/vc-module-pricing#40]
1. The "Price list assignments" blade is too narrow. Sometimes it's really hard to distinguish entries there:
![image](https://user-images.githubusercontent.com/1835759/52111991-d3cd1380-2637-11e9-9da1-bfcd752f4df8.png)
2. "Enable date" and "Expiration date" values are important for pricelist assignments, so these values should be added as columns to the "Price list assignments" blade. It's really hard to find expired assignments in the current implementation.
3. On some projects (like HRU), users have to remove all prices, and removing them takes lots of time when having hundreds or thousands of pricelists. So, "Price lists" and "Price list assignments" blades should probably have a command to remove all pricelists or pricelist assignments, respectively.
4. It would be nice to have custom sorting for columns and some kind of search/filter functionality, e.g. to display only the pricelists or pricelist assignments with given substring in their name.

**Comment by yecli** [comment]
Proposed changes:
1. Need to add "startDate" and "endDate" to columns list in assignment-list.tpl.html
2. Add search filter to Price list and Price list assignment blades to filter content by keyword, like for Categories/Products in Catalog module.

Regarding other requested changes, let me ask couple of questions:
1. Make tab wide - user can maximize it from UI. Do not know if it is common problem for the projects that it should be maximized by default.
3. About "Delete all". I did not find "Delete all" functionality in any other modules. Do you think it is really needed in many projects to be added to platform, not to be as extended in project modules? Regarding implementation details - probably it could be implemented as background job, like building search index, as for huge number of price lists deletion could take some time.
4. Could you give more details on custom sorting, maybe an example?

**Comment by yecli** [comment]
Released in [v2.18.4](https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/v2.18.4).
