### ISSUE TITLE
Bug with price evaluation for user groups

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-pricing#42]
one user has "MOT" usergroup on Contact level and there is "Test_Expiry Date" price-list with the same tag;
second type of the users has "GT" usergroup and there is "Day2 pricelist" with the same tag.
Problem:
WHEN user who belongs to "GT" user group THEN he sees the prices "Test_Expiry Date" price-list tagged with "MOT" group.
 
Expected:
WHEN user who belongs to "GT" user group THEN he must see the prices from "Day2 pricelist" price-list tagged with "GT" group.

**Comment by yecli** [comment]
Tried described setup on platform 2.13.43 and latest modules. Got proper prices on storefront for both group contacts.

**Comment by yecli** [comment]
Closing as it seems it is not actual now.
