### ISSUE TITLE
Error "request too long"

### ISSUE THREAD

**Issue by alexx1524** [VirtoCommerce/vc-module-pricing#74]
The problem arises from the fact that you configure the search criteria is passed in the request Uri. And when requesting an array of product IDs with a number greater than 32, the maximum length of the Get request is exceeded.

        /// <summary>
        /// Search product prices 
        /// </summary>
        /// <remarks>Search product prices</remarks>
        [HttpGet]
        [ResponseType(typeof(PricingSearchResult<webModel.ProductPrice>))]
        [Route("api/catalog/products/prices/search")]
        public IHttpActionResult SearchProductPrices([FromUri]PricesSearchCriteria criteria)

**We would like to get another method (**HttpPost**) with the same functionality in the next version of the module, only Search criteria should be passed in the request body.**

**Comment by yecli** [comment]
Released in https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/v2.18.12
