### ISSUE TITLE
When Virto have more than 20 catalogs, the product prices page could not display

### ISSUE THREAD

**Issue by zhangpengchen** [VirtoCommerce/vc-module-pricing#84]
Virto Commerce V3 RC 5

When Virto have more than 20 catalogs, the product prices page could not display.
There is a console error when opening a product prices page `Cannot read property 'name' of undefined`

Due to `catalogs.getCatalogs` only return 20 catalogs not all.
https://github.com/VirtoCommerce/vc-module-pricing/blob/b51b44957fc9e44f470886db5335bdb3d1aec23b/src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.js#L13

Related issue: https://github.com/VirtoCommerce/vc-module-catalog/issues/348

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-pricing/releases/tag/3.17.0
