### ISSUE TITLE
Product prices bug with validation 

### ISSUE THREAD

**Issue by tatarincev** [VirtoCommerce/vc-module-pricing#9]
How to reproduce:

Open product price widget for any product.
Change one pricelist price and click save.
Try to edit price again, get a validation error for all prices.
![image](https://user-images.githubusercontent.com/7566324/30541199-9a4c08d4-9c7a-11e7-8a54-4dd9ff99b487.png)

**Comment by megafreeman** [comment]
Fixed error in min quantity validation process by [commit](https://github.com/VirtoCommerce/vc-module-pricing/commit/35945ccb34fdb26b467601f06563f7bb45b0adef)

**Comment by tatarincev** [comment]
@megafreeman  Related to this changes - https://github.com/VirtoCommerce/vc-module-pricing/commit/35945ccb34fdb26b467601f06563f7bb45b0adef#diff-e5bd7c73a54c67abcdd513dfce59166aR172. 
The best solution for checking the uniqueness constraint is a comparison of the strings resulting from the sum of the price .priceListId + "-" + price.quantity.
